class_name Kit
## The level-building toolbox. Static functions that create textured, collidable
## geometry, lights, labels and triggers under a parent node.
##
## Conventions
## * Textures are named "group/name" (see assets/textures, generated by
##   tools/gen_assets/textures.py). A missing texture becomes a magenta checker
##   and a warning, never a crash.
## * `tile` is the world size in metres that one texture repeat covers (2 m by
##   default), so neighbouring pieces line up.
## * Everything solid gets a StaticBody3D on physics layer 1 with meta
##   "surface" set from the texture manifest (footstep sounds).
## * Positions are centres unless the function says otherwise. Yaw is in
##   degrees around +Y (0 faces -Z / north).

const TEX_ROOT := "res://assets/textures/"
const L_WORLD := 1
const L_INTERACT := 4
const L_TRIGGER := 8
const L_BIG_ONLY := 16
const L_MIRROR_ONLY := 32
const L_CUTTABLE := 64
const L_NPC := 128
const L_NORMAL_ONLY := 256
const L_LANTERN_ONLY := 512

static var ps1_enabled := true
static var default_tile := 2.0
static var _tex_cache: Dictionary = {}
static var _mat_cache: Dictionary = {}
static var _manifest: Dictionary = {}
static var _manifest_loaded := false
static var _shaders: Dictionary = {}
static var _white: Texture2D = null


# --- textures & materials -------------------------------------------------

## Drop cached resources (called when the game quits so nothing leaks at exit).
static func clear_caches() -> void:
	_tex_cache.clear()
	_mat_cache.clear()
	_shaders.clear()
	_white = null

static func manifest() -> Dictionary:
	if not _manifest_loaded:
		_manifest_loaded = true
		var p := TEX_ROOT + "manifest.json"
		if FileAccess.file_exists(p):
			var f := FileAccess.open(p, FileAccess.READ)
			var parsed = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				_manifest = parsed
	return _manifest


static func surface_of(tex_name: String) -> String:
	var m := manifest()
	if m.has(tex_name):
		return String(m[tex_name].get("surface", "stone"))
	return "stone"


static func has_alpha(tex_name: String) -> bool:
	var m := manifest()
	if m.has(tex_name):
		return bool(m[tex_name].get("alpha", false))
	return false


static func tex(tex_name: String) -> Texture2D:
	if _tex_cache.has(tex_name):
		return _tex_cache[tex_name]
	var path := TEX_ROOT + tex_name + ".png"
	var t: Texture2D = null
	if ResourceLoader.exists(path):
		t = load(path)
	if t == null:
		push_warning("Kit: missing texture '%s' (using checker)" % tex_name)
		t = _checker()
	_tex_cache[tex_name] = t
	return t


static func _checker() -> Texture2D:
	if _tex_cache.has("__checker"):
		return _tex_cache["__checker"]
	var img := Image.create(16, 16, false, Image.FORMAT_RGB8)
	for y in 16:
		for x in 16:
			img.set_pixel(x, y, Color.MAGENTA if ((x / 4 + y / 4) % 2 == 0) else Color.BLACK)
	var t := ImageTexture.create_from_image(img)
	_tex_cache["__checker"] = t
	return t


static func white_tex() -> Texture2D:
	if _white == null:
		var img := Image.create(4, 4, false, Image.FORMAT_RGB8)
		img.fill(Color.WHITE)
		_white = ImageTexture.create_from_image(img)
	return _white


static func shader(kind: String) -> Shader:
	if _shaders.has(kind):
		return _shaders[kind]
	var s: Shader = load("res://src/shaders/%s.gdshader" % kind)
	_shaders[kind] = s
	return s


## A material for a named texture.
## opts: tint (Color), unshaded (bool), double (bool), emission (Color),
## emission_energy (float), alpha (bool: force alpha scissor), uv_scale (Vector2),
## uv_offset (Vector2), vertex_color (bool), affine (float), snap (float),
## specular (float), scroll (Vector2), transparent (bool, alpha blend via Standard).
## How much nearer the eye a floor or ceiling is drawn than the geometry it
## shares a plane with (a fraction of its distance: 5 mm at ten metres).
## Overlays on a floor (rings, path patches) use more, see _mat_opts.
const FLOOR_BIAS := 0.0005


static func mat(tex_name: String, opts: Dictionary = {}) -> Material:
	var key := tex_name + "|" + str(opts)
	if _mat_cache.has(key):
		return _mat_cache[key]
	var m: Material
	var alpha := bool(opts.get("alpha", has_alpha(tex_name)))
	var t: Texture2D = tex(tex_name) if tex_name != "" else white_tex()
	if ps1_enabled and not opts.get("transparent", false):
		var kind := "ps1"
		var unshaded := bool(opts.get("unshaded", false))
		var double := bool(opts.get("double", alpha))
		if unshaded and double:
			kind = "ps1_unshaded_double"
		elif unshaded:
			kind = "ps1_unshaded"
		elif double:
			kind = "ps1_double"
		var sm := ShaderMaterial.new()
		sm.shader = shader(kind)
		sm.set_shader_parameter("albedo_tex", t)
		sm.set_shader_parameter("tint", opts.get("tint", Color.WHITE))
		sm.set_shader_parameter("uv_scale", opts.get("uv_scale", Vector2.ONE))
		sm.set_shader_parameter("uv_offset", opts.get("uv_offset", Vector2.ZERO))
		if opts.has("emission"):
			sm.set_shader_parameter("emission", opts.emission)
			sm.set_shader_parameter("emission_energy", float(opts.get("emission_energy", 1.0)))
		sm.set_shader_parameter("alpha_scissor", 0.5 if alpha else 0.0)
		sm.set_shader_parameter("use_vertex_color", bool(opts.get("vertex_color", false)))
		sm.set_shader_parameter("affine", float(opts.get("affine", 0.35)))
		sm.set_shader_parameter("depth_bias", float(opts.get("depth_bias", 0.0)))
		sm.set_shader_parameter("snap", float(opts.get("snap", 200.0)))
		sm.set_shader_parameter("specular_amt", float(opts.get("specular", 0.05)))
		if opts.has("scroll"):
			var sc: Vector2 = opts.scroll
			sm.set_shader_parameter("scroll_x", sc.x)
			sm.set_shader_parameter("scroll_y", sc.y)
		m = sm
	else:
		var st := StandardMaterial3D.new()
		st.albedo_texture = t
		st.albedo_color = opts.get("tint", Color.WHITE)
		st.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
		st.roughness = 1.0
		st.metallic = 0.0
		st.metallic_specular = float(opts.get("specular", 0.05))
		st.vertex_color_use_as_albedo = bool(opts.get("vertex_color", false))
		var uvs: Vector2 = opts.get("uv_scale", Vector2.ONE)
		st.uv1_scale = Vector3(uvs.x, uvs.y, 1.0)
		if opts.get("unshaded", false):
			st.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
		if opts.get("transparent", false):
			st.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		elif alpha:
			st.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_SCISSOR
			st.alpha_scissor_threshold = 0.5
		if alpha or opts.get("double", false):
			st.cull_mode = BaseMaterial3D.CULL_DISABLED
		if opts.has("emission"):
			st.emission_enabled = true
			st.emission = opts.emission
			st.emission_energy_multiplier = float(opts.get("emission_energy", 1.0))
		m = st
	_mat_cache[key] = m
	return m


## A flat-coloured material (no texture).
static func flat(color: Color, opts: Dictionary = {}) -> Material:
	var o := opts.duplicate()
	o["tint"] = color
	return mat("", o)


## A material for vertex-coloured props.
static func vertex_mat(opts: Dictionary = {}) -> Material:
	var o := opts.duplicate()
	o["vertex_color"] = true
	return mat("", o)


static func water_mat(tex_name: String = "nature/water_dark", opts: Dictionary = {}) -> ShaderMaterial:
	var sm := ShaderMaterial.new()
	sm.shader = shader("water")
	sm.set_shader_parameter("albedo_tex", tex(tex_name))
	sm.set_shader_parameter("tint", opts.get("tint", Color(1, 1, 1, 0.85)))
	sm.set_shader_parameter("uv_scale", float(opts.get("uv_scale", 0.25)))
	sm.set_shader_parameter("speed", float(opts.get("speed", 0.02)))
	sm.set_shader_parameter("swell", float(opts.get("swell", 0.06)))
	sm.set_shader_parameter("glow", float(opts.get("glow", 0.0)))
	return sm


static func static_mat(opts: Dictionary = {}) -> ShaderMaterial:
	var sm := ShaderMaterial.new()
	sm.shader = shader("static")
	sm.set_shader_parameter("tint", opts.get("tint", Color.WHITE))
	sm.set_shader_parameter("scale", float(opts.get("scale", 120.0)))
	sm.set_shader_parameter("brightness", float(opts.get("brightness", 1.0)))
	return sm


static func mirror_mat(tex_name: String = "props/mirror", opts: Dictionary = {}) -> ShaderMaterial:
	var sm := ShaderMaterial.new()
	sm.shader = shader("mirror")
	sm.set_shader_parameter("albedo_tex", tex(tex_name))
	sm.set_shader_parameter("tint", opts.get("tint", Color(0.6, 0.7, 0.75, 1.0)))
	return sm


# --- mesh helpers -----------------------------------------------------------

## Adds a MeshInstance3D and (optionally) a static collision body.
## opts: solid (bool, default true), shape ("box"|"trimesh"|"none"), size (for box),
## layer (visual layer bits), collision_layer (physics bits), surface (String), name, cast_shadow (bool)
static func add_mesh(parent: Node, mesh: Mesh, material: Material, pos: Vector3, opts: Dictionary = {}) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	if material != null:
		mi.material_override = material
	mi.position = pos
	if opts.has("yaw"):
		mi.rotation.y = deg_to_rad(float(opts.yaw))
	if opts.has("rotation"):
		mi.rotation_degrees = opts.rotation
	if opts.has("layer"):
		mi.layers = int(opts.layer)
	if opts.has("name"):
		mi.name = String(opts.name)
	if not bool(opts.get("cast_shadow", true)):
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	parent.add_child(mi)
	if bool(opts.get("solid", true)):
		var shape_kind := String(opts.get("shape", "box"))
		var body := StaticBody3D.new()
		body.collision_layer = int(opts.get("collision_layer", L_WORLD))
		body.collision_mask = 0
		body.set_meta("surface", String(opts.get("surface", "stone")))
		var cs := CollisionShape3D.new()
		if shape_kind == "trimesh":
			cs.shape = mesh.create_trimesh_shape()
		elif shape_kind == "box":
			var bs := BoxShape3D.new()
			bs.size = opts.get("size", mesh.get_aabb().size)
			cs.shape = bs
			cs.position = opts.get("shape_offset", mesh.get_aabb().get_center())
		elif shape_kind == "none":
			cs = null
		if cs != null:
			body.add_child(cs)
			mi.add_child(body)
	return mi


## Build a mesh from quads via SurfaceTool. quads: Array of [a,b,c,d,uva,uvb,uvc,uvd,normal] (CCW).
static func mesh_from_quads(quads: Array, colors: Array = []) -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var vi := 0
	for qi in quads.size():
		var q: Array = quads[qi]
		var n: Vector3 = q[8]
		var col: Color = colors[qi] if qi < colors.size() else Color.WHITE
		for k in [0, 1, 2, 0, 2, 3]:
			st.set_normal(n)
			st.set_uv(q[4 + k])
			st.set_color(col)
			st.add_vertex(q[k])
			vi += 1
	st.index()
	return st.commit()


static func _face(a: Vector3, b: Vector3, c: Vector3, d: Vector3, uva: Vector2, uvb: Vector2, uvc: Vector2, uvd: Vector2, n: Vector3) -> Array:
	return [a, b, c, d, uva, uvb, uvc, uvd, n]


## Quads for an axis-aligned box centred at `c` with world-space tiling.
## faces: subset of ["px","nx","py","ny","pz","nz"] (all when empty).
static func box_quads(c: Vector3, s: Vector3, tile: float, faces: Array = [], uv_origin: Vector3 = Vector3.ZERO) -> Array:
	var h := s * 0.5
	var x0 := c.x - h.x
	var x1 := c.x + h.x
	var y0 := c.y - h.y
	var y1 := c.y + h.y
	var z0 := c.z - h.z
	var z1 := c.z + h.z
	var out: Array = []
	var t := 1.0 / tile
	var o := uv_origin
	# Godot front faces are CLOCKWISE as seen from the visible side (verified by
	# tools/winding_probe.gd), so each face is wound clockwise as seen from
	# outside the box; the normal points outward.
	if faces.is_empty() or "pz" in faces:
		out.append(_face(Vector3(x0, y0, z1), Vector3(x0, y1, z1), Vector3(x1, y1, z1), Vector3(x1, y0, z1),
			Vector2((x0 - o.x) * t, (y1 - y0) * t), Vector2((x0 - o.x) * t, 0), Vector2((x1 - o.x) * t, 0), Vector2((x1 - o.x) * t, (y1 - y0) * t), Vector3(0, 0, 1)))
	if faces.is_empty() or "nz" in faces:
		out.append(_face(Vector3(x1, y0, z0), Vector3(x1, y1, z0), Vector3(x0, y1, z0), Vector3(x0, y0, z0),
			Vector2((-x1 - o.x) * t, (y1 - y0) * t), Vector2((-x1 - o.x) * t, 0), Vector2((-x0 - o.x) * t, 0), Vector2((-x0 - o.x) * t, (y1 - y0) * t), Vector3(0, 0, -1)))
	if faces.is_empty() or "px" in faces:
		out.append(_face(Vector3(x1, y0, z1), Vector3(x1, y1, z1), Vector3(x1, y1, z0), Vector3(x1, y0, z0),
			Vector2((-z1 - o.z) * t, (y1 - y0) * t), Vector2((-z1 - o.z) * t, 0), Vector2((-z0 - o.z) * t, 0), Vector2((-z0 - o.z) * t, (y1 - y0) * t), Vector3(1, 0, 0)))
	if faces.is_empty() or "nx" in faces:
		out.append(_face(Vector3(x0, y0, z0), Vector3(x0, y1, z0), Vector3(x0, y1, z1), Vector3(x0, y0, z1),
			Vector2((z0 - o.z) * t, (y1 - y0) * t), Vector2((z0 - o.z) * t, 0), Vector2((z1 - o.z) * t, 0), Vector2((z1 - o.z) * t, (y1 - y0) * t), Vector3(-1, 0, 0)))
	if faces.is_empty() or "py" in faces:
		out.append(_face(Vector3(x0, y1, z0), Vector3(x1, y1, z0), Vector3(x1, y1, z1), Vector3(x0, y1, z1),
			Vector2((x0 - o.x) * t, (z0 - o.z) * t), Vector2((x1 - o.x) * t, (z0 - o.z) * t), Vector2((x1 - o.x) * t, (z1 - o.z) * t), Vector2((x0 - o.x) * t, (z1 - o.z) * t), Vector3(0, 1, 0)))
	if faces.is_empty() or "ny" in faces:
		out.append(_face(Vector3(x0, y0, z1), Vector3(x1, y0, z1), Vector3(x1, y0, z0), Vector3(x0, y0, z0),
			Vector2((x0 - o.x) * t, (z1 - o.z) * t), Vector2((x1 - o.x) * t, (z1 - o.z) * t), Vector2((x1 - o.x) * t, (z0 - o.z) * t), Vector2((x0 - o.x) * t, (z0 - o.z) * t), Vector3(0, -1, 0)))
	return out


## A textured, solid box. opts: tile, faces, solid, layer, collision_layer, mat (override), tint, unshaded, emission, name
static func box(parent: Node, pos: Vector3, size: Vector3, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var tile := float(opts.get("tile", default_tile))
	var quads := box_quads(Vector3.ZERO, size, tile, opts.get("faces", []), -pos)
	var mesh := mesh_from_quads(quads)
	var material: Material = opts.get("mat", mat(tex_name, _mat_opts(opts)))
	var o := opts.duplicate()
	o["size"] = size
	o["shape_offset"] = Vector3.ZERO
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	return add_mesh(parent, mesh, material, pos, o)


static func _mat_opts(opts: Dictionary) -> Dictionary:
	var o := {}
	for k in ["tint", "unshaded", "double", "emission", "emission_energy", "alpha", "uv_scale", "uv_offset", "vertex_color", "affine", "snap", "specular", "scroll", "transparent", "depth_bias"]:
		if opts.has(k):
			o[k] = opts[k]
	# an overlay lies on another surface (a path on the ground, a rug, a stain):
	# it is drawn a touch nearer the eye so the two never flicker
	if bool(opts.get("overlay", false)) and not o.has("depth_bias"):
		o["depth_bias"] = 0.004
	return o


## A floor slab (top face textured, thin collision). size is (width, depth).
static func floor(parent: Node, pos: Vector3, size: Vector2, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var thick := float(opts.get("thick", 0.2))
	var o := opts.duplicate()
	o["faces"] = ["py"] if not opts.get("all_faces", false) else []
	# a floor lies over whatever else was built to its height (the top of a
	# wall, a terrain cell): drawn a hair nearer the eye, it is the one seen
	if not o.has("depth_bias") and not o.has("overlay"):
		o["depth_bias"] = FLOOR_BIAS
	return box(parent, pos - Vector3(0, thick * 0.5, 0), Vector3(size.x, thick, size.y), tex_name, o)


## A ceiling slab (bottom face textured).
static func ceiling(parent: Node, pos: Vector3, size: Vector2, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var thick := float(opts.get("thick", 0.2))
	var o := opts.duplicate()
	o["faces"] = ["ny"] if not opts.get("all_faces", false) else []
	if not o.has("cast_shadow"):
		o["cast_shadow"] = false
	if not o.has("depth_bias") and not o.has("overlay"):
		o["depth_bias"] = FLOOR_BIAS
	return box(parent, pos + Vector3(0, thick * 0.5, 0), Vector3(size.x, thick, size.y), tex_name, o)


## A wall between two ground points. opts: thick (0.2), tile, y (base height), name
static func wall(parent: Node, from: Vector3, to: Vector3, height: float, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var thick := float(opts.get("thick", 0.2))
	var d := to - from
	d.y = 0.0
	var length := d.length()
	if length < 0.001:
		return null
	var mid := (from + to) * 0.5 + Vector3(0, height * 0.5, 0)
	var yaw := atan2(-d.x, -d.z) + PI * 0.5
	# Build along local X then rotate.
	var tile := float(opts.get("tile", default_tile))
	var quads := box_quads(Vector3.ZERO, Vector3(length, height, thick), tile, opts.get("faces", []), Vector3(-length * 0.5, -height, 0))
	var mesh := mesh_from_quads(quads)
	var material: Material = opts.get("mat", mat(tex_name, _mat_opts(opts)))
	var o := opts.duplicate()
	o["size"] = Vector3(length, height, thick)
	o["shape_offset"] = Vector3.ZERO
	o["yaw"] = rad_to_deg(yaw)
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	return add_mesh(parent, mesh, material, mid, o)


## A single quad. Godot front faces are CLOCKWISE as seen from the front, so pass
## a, b, c, d going clockwise when looking at the visible side.
static func quad(parent: Node, a: Vector3, b: Vector3, c: Vector3, d: Vector3, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	# clockwise-from-front winding means the outward normal is (c - a) x (b - a)
	var n := (c - a).cross(b - a).normalized()
	var uvs: Array = opts.get("uvs", [Vector2(0, 1), Vector2(1, 1), Vector2(1, 0), Vector2(0, 0)])
	var mesh := mesh_from_quads([_face(a, b, c, d, uvs[0], uvs[1], uvs[2], uvs[3], n)])
	var material: Material = opts.get("mat", mat(tex_name, _mat_opts(opts)))
	var o := opts.duplicate()
	if not o.has("shape"):
		o["shape"] = "trimesh"
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	return add_mesh(parent, mesh, material, Vector3.ZERO, o)


## A flat picture/sign on a wall: centre position, yaw (facing direction), size (w, h).
static func sign(parent: Node, tex_name: String, pos: Vector3, yaw_deg: float, size: Vector2, opts: Dictionary = {}) -> MeshInstance3D:
	var pm := QuadMesh.new()
	pm.size = size
	var o := opts.duplicate()
	if not o.has("solid"):
		o["solid"] = false
	# QuadMesh faces +Z; the Kit's yaw convention faces -Z.
	o["yaw"] = yaw_deg + 180.0
	var mo := _mat_opts(opts)
	if not mo.has("double"):
		mo["double"] = true
	var material: Material = opts.get("mat", mat(tex_name, mo))
	return add_mesh(parent, pm, material, pos, o)


## Vertical cylinder (pillars, trunks, wells).
static func cylinder(parent: Node, pos: Vector3, radius: float, height: float, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var cm := CylinderMesh.new()
	cm.top_radius = float(opts.get("top_radius", radius))
	cm.bottom_radius = radius
	cm.height = height
	cm.radial_segments = int(opts.get("segments", 8))
	cm.rings = 1
	var o := opts.duplicate()
	if not o.has("shape"):
		o["shape"] = "cylinder"
	var mo := _mat_opts(opts)
	if not mo.has("uv_scale"):
		var tile := float(opts.get("tile", default_tile))
		mo["uv_scale"] = Vector2(maxf(1.0, roundf(TAU * radius / tile)), maxf(0.5, height / tile))
	var material: Material = opts.get("mat", mat(tex_name, mo))
	var mi := add_mesh(parent, cm, material, pos + Vector3(0, height * 0.5, 0), _no_solid(o))
	if bool(opts.get("solid", true)):
		var body := StaticBody3D.new()
		body.collision_layer = int(opts.get("collision_layer", L_WORLD))
		body.collision_mask = 0
		body.set_meta("surface", String(opts.get("surface", surface_of(tex_name))))
		var cs := CollisionShape3D.new()
		var sh := CylinderShape3D.new()
		sh.radius = maxf(radius, cm.top_radius)
		sh.height = height
		cs.shape = sh
		body.add_child(cs)
		mi.add_child(body)
	return mi


static func _no_solid(o: Dictionary) -> Dictionary:
	var d := o.duplicate()
	d["solid"] = false
	return d


## Stairs made of boxes. Rises along -Z of local yaw. width across, each step depth/height.
static func stairs(parent: Node, pos: Vector3, yaw_deg: float, width: float, steps: int, step_h: float, step_d: float, tex_name: String, opts: Dictionary = {}) -> Node3D:
	var root := Node3D.new()
	root.position = pos
	root.rotation.y = deg_to_rad(yaw_deg)
	root.name = String(opts.get("name", "Stairs"))
	parent.add_child(root)
	# step_h < 0 builds a descending flight (each tread is a box down to below the lowest step)
	var lo := (step_h * steps - 0.3) if step_h < 0.0 else 0.0
	for i in steps:
		var top := step_h * (i + 1)
		var hgt := top - lo
		var c := Vector3(0, (top + lo) * 0.5, -(i + 0.5) * step_d)
		var o := opts.duplicate()
		o.erase("name")
		box(root, c, Vector3(width, hgt, step_d), tex_name, o)
	return root


## A ramp (sloped box) rising along -Z of local yaw from height 0 to `rise` over `length`.
static func ramp(parent: Node, pos: Vector3, yaw_deg: float, width: float, length: float, rise: float, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var thick := 0.2
	var a := Vector3(-width * 0.5, 0, 0)
	var b := Vector3(width * 0.5, 0, 0)
	var c := Vector3(width * 0.5, rise, -length)
	var d := Vector3(-width * 0.5, rise, -length)
	var tile := float(opts.get("tile", default_tile))
	var slope_len := Vector2(length, rise).length()
	var quads := [
		_face(a, d, c, b, Vector2(0, 0), Vector2(0, slope_len / tile), Vector2(width / tile, slope_len / tile), Vector2(width / tile, 0), (b - a).cross(d - a).normalized()),
		_face(a + Vector3(0, -thick, 0), b + Vector3(0, -thick, 0), c + Vector3(0, -thick, 0), d + Vector3(0, -thick, 0), Vector2(0, 0), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1), Vector3(0, -1, 0)),
		_face(a, a + Vector3(0, -thick, 0), d + Vector3(0, -thick, 0), d, Vector2(0, 0), Vector2(0, thick / tile), Vector2(slope_len / tile, thick / tile), Vector2(slope_len / tile, 0), Vector3(-1, 0, 0)),
		_face(b, c, c + Vector3(0, -thick, 0), b + Vector3(0, -thick, 0), Vector2(0, 0), Vector2(slope_len / tile, 0), Vector2(slope_len / tile, thick / tile), Vector2(0, thick / tile), Vector3(1, 0, 0)),
		_face(c, c + Vector3(0, -thick, 0), d + Vector3(0, -thick, 0), d, Vector2(0, 0), Vector2(0, thick / tile), Vector2(width / tile, thick / tile), Vector2(width / tile, 0), Vector3(0, 0, -1)),
	]
	var mesh := mesh_from_quads(quads)
	var o := opts.duplicate()
	o["shape"] = "trimesh"
	o["yaw"] = yaw_deg
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	return add_mesh(parent, mesh, opts.get("mat", mat(tex_name, _mat_opts(opts))), pos, o)


## A pointed/rounded archway built from boxes: two posts, a lintel, corner fills. Opening is width x height.
static func arch(parent: Node, pos: Vector3, yaw_deg: float, width: float, height: float, tex_name: String, opts: Dictionary = {}) -> Node3D:
	var root := Node3D.new()
	root.position = pos
	root.rotation.y = deg_to_rad(yaw_deg)
	root.name = String(opts.get("name", "Arch"))
	parent.add_child(root)
	var post := float(opts.get("post", 0.5))
	var depth := float(opts.get("depth", 0.6))
	var top := float(opts.get("top", 0.6))
	var o := opts.duplicate()
	o.erase("name")
	box(root, Vector3(-(width * 0.5 + post * 0.5), height * 0.5, 0), Vector3(post, height, depth), tex_name, o)
	box(root, Vector3((width * 0.5 + post * 0.5), height * 0.5, 0), Vector3(post, height, depth), tex_name, o)
	box(root, Vector3(0, height + top * 0.5, 0), Vector3(width + post * 2.0, top, depth), tex_name, o)
	if bool(opts.get("pointed", true)):
		var fill := width * 0.22
		box(root, Vector3(-(width * 0.5 - fill * 0.5), height - fill * 0.35, 0), Vector3(fill, fill * 0.7, depth * 0.98), tex_name, o)
		box(root, Vector3((width * 0.5 - fill * 0.5), height - fill * 0.35, 0), Vector3(fill, fill * 0.7, depth * 0.98), tex_name, o)
		box(root, Vector3(0, height - fill * 0.12, 0), Vector3(width * 0.4, fill * 0.24, depth * 0.98), tex_name, o)
	return root


## Heightmap terrain. `height_fn.call(x, z) -> float`, `color_fn.call(x, z, h) -> Color` (optional).
## opts.holes: Array of Rect2 (world x, z) whose cells are left out of mesh and
## collision both, for a stair or a cellar that has to go down through the ground.
static func terrain(parent: Node, pos: Vector3, size: Vector2, res: int, height_fn: Callable, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var tile := float(opts.get("tile", default_tile))
	var color_fn: Callable = opts.get("color_fn", Callable())
	var w := size.x
	var d := size.y
	var heights: Array = []
	for j in res + 1:
		var row: Array = []
		for i in res + 1:
			var x := -w * 0.5 + w * i / res
			var z := -d * 0.5 + d * j / res
			row.append(float(height_fn.call(x + pos.x, z + pos.z)))
		heights.append(row)
	var verts: Array = []
	for j in res + 1:
		var vrow: Array = []
		for i in res + 1:
			var x := -w * 0.5 + w * i / res
			var z := -d * 0.5 + d * j / res
			vrow.append(Vector3(x, heights[j][i], z))
		verts.append(vrow)
	var holes: Array = opts.get("holes", [])
	for j in res:
		for i in res:
			var a: Vector3 = verts[j][i]
			var b: Vector3 = verts[j][i + 1]
			var c: Vector3 = verts[j + 1][i + 1]
			var dd: Vector3 = verts[j + 1][i]
			if not holes.is_empty():
				var centre := Vector2((a.x + c.x) * 0.5 + pos.x, (a.z + c.z) * 0.5 + pos.z)
				var skip := false
				for h in holes:
					if (h as Rect2).has_point(centre):
						skip = true
				if skip:
					continue
			var tris := [[a, b, c], [a, c, dd]] if (i + j) % 2 == 0 else [[a, b, dd], [b, c, dd]]
			for tri in tris:
				var n: Vector3 = (tri[2] - tri[0]).cross(tri[1] - tri[0]).normalized()
				for v in tri:
					st.set_normal(n)
					st.set_uv(Vector2((v.x + pos.x) / tile, (v.z + pos.z) / tile))
					if color_fn.is_valid():
						st.set_color(color_fn.call(v.x + pos.x, v.z + pos.z, v.y))
					else:
						st.set_color(Color.WHITE)
					st.add_vertex(v)
	var mesh := st.commit()
	var o := opts.duplicate()
	o["shape"] = "trimesh"
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	var mo := _mat_opts(opts)
	if color_fn.is_valid():
		mo["vertex_color"] = true
	return add_mesh(parent, mesh, opts.get("mat", mat(tex_name, mo)), pos, o)


## A water plane (no collision by default; opts.solid to make it walkable).
static func water(parent: Node, pos: Vector3, size: Vector2, tex_name: String = "nature/water_dark", opts: Dictionary = {}) -> MeshInstance3D:
	var pm := PlaneMesh.new()
	pm.size = size
	pm.subdivide_width = int(opts.get("subdiv", 8))
	pm.subdivide_depth = int(opts.get("subdiv", 8))
	var o := opts.duplicate()
	if not o.has("solid"):
		o["solid"] = false
	o["surface"] = "water"
	o["shape"] = "box"
	o["size"] = Vector3(size.x, 0.1, size.y)
	o["cast_shadow"] = false
	var m := water_mat(tex_name, opts)
	var mi := add_mesh(parent, pm, m, pos, o)
	mi.set_meta("water", true)
	return mi


# --- lights, labels, triggers ------------------------------------------------

static func light(parent: Node, pos: Vector3, color: Color = Color(1, 0.85, 0.6), energy: float = 1.2, range_: float = 8.0, shadows: bool = false) -> OmniLight3D:
	var l := OmniLight3D.new()
	l.position = pos
	l.light_color = color
	l.light_energy = energy
	l.omni_range = range_
	l.omni_attenuation = 1.3
	l.shadow_enabled = shadows
	parent.add_child(l)
	return l


static func spot(parent: Node, pos: Vector3, target: Vector3, color: Color, energy: float = 2.0, range_: float = 12.0, angle: float = 40.0) -> SpotLight3D:
	var l := SpotLight3D.new()
	l.position = pos
	l.light_color = color
	l.light_energy = energy
	l.spot_range = range_
	l.spot_angle = angle
	parent.add_child(l)
	l.look_at_from_position(pos, target, Vector3.UP if absf((target - pos).normalized().y) < 0.99 else Vector3.RIGHT)
	return l


static func sun(parent: Node, pitch_deg: float, yaw_deg: float, color: Color, energy: float, shadows: bool = true) -> DirectionalLight3D:
	var l := DirectionalLight3D.new()
	l.rotation_degrees = Vector3(pitch_deg, yaw_deg, 0)
	l.light_color = color
	l.light_energy = energy
	l.shadow_enabled = shadows
	l.directional_shadow_mode = DirectionalLight3D.SHADOW_ORTHOGONAL
	l.directional_shadow_max_distance = 60.0
	parent.add_child(l)
	return l


## Text in the world. kind: "title" | "display" | "body".
static func label(parent: Node, text: String, pos: Vector3, yaw_deg: float, size: int = 48, color: Color = Color(0.9, 0.85, 0.7), kind: String = "display", opts: Dictionary = {}) -> Label3D:
	var l := Label3D.new()
	l.text = text
	l.font = UITheme.font(kind)
	l.font_size = size
	l.modulate = color
	l.position = pos
	# Label3D faces +Z; the Kit's yaw convention faces -Z.
	l.rotation.y = deg_to_rad(yaw_deg + 180.0)
	l.pixel_size = float(opts.get("pixel_size", 0.01))
	l.billboard = BaseMaterial3D.BILLBOARD_ENABLED if opts.get("billboard", false) else BaseMaterial3D.BILLBOARD_DISABLED
	l.shaded = false
	l.double_sided = bool(opts.get("double", true))
	l.texture_filter = BaseMaterial3D.TEXTURE_FILTER_NEAREST
	l.outline_size = int(opts.get("outline", 4))
	l.outline_modulate = opts.get("outline_color", Color(0, 0, 0, 0.8))
	l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	if opts.has("layer"):
		l.layers = int(opts.layer)
	parent.add_child(l)
	return l


## Invisible solid box (barriers, mouse-gap blockers on other layers).
static func blocker(parent: Node, pos: Vector3, size: Vector3, collision_layer: int = L_WORLD, surface: String = "stone") -> StaticBody3D:
	var body := StaticBody3D.new()
	body.position = pos
	body.collision_layer = collision_layer
	body.collision_mask = 0
	body.set_meta("surface", surface)
	var cs := CollisionShape3D.new()
	var bs := BoxShape3D.new()
	bs.size = size
	cs.shape = bs
	body.add_child(cs)
	parent.add_child(body)
	return body


## Trigger volume. `on_enter.call(player)` when the player walks in; optional `on_exit`.
## opts: once (bool), name, radius (sphere instead of box), yaw
static func trigger(parent: Node, pos: Vector3, size: Vector3, on_enter: Callable, opts: Dictionary = {}) -> Area3D:
	var a := Area3D.new()
	a.position = pos
	a.collision_layer = 0
	a.collision_mask = 2
	a.monitorable = false
	a.name = String(opts.get("name", "Trigger"))
	if opts.has("yaw"):
		a.rotation.y = deg_to_rad(float(opts.yaw))
	var cs := CollisionShape3D.new()
	if opts.has("radius"):
		var ss := SphereShape3D.new()
		ss.radius = float(opts.radius)
		cs.shape = ss
	else:
		var bs := BoxShape3D.new()
		bs.size = size
		cs.shape = bs
	a.add_child(cs)
	parent.add_child(a)
	var once := bool(opts.get("once", false))
	var born := Time.get_ticks_msec()
	if bool(opts.get("continuous", false)):
		# fire for the player every tenth of a second while they are inside,
		# not only on the way in (the backwards door needs to see you turn round)
		var t := Timer.new()
		t.wait_time = 0.1
		t.autostart = true
		a.add_child(t)
		t.timeout.connect(func() -> void:
			if Time.get_ticks_msec() - born < 400:
				return
			for body in a.get_overlapping_bodies():
				if body is Player:
					on_enter.call(body))
		return a
	a.body_entered.connect(func(body: Node3D) -> void:
		if body is Player:
			if Time.get_ticks_msec() - born < 400:
				return
			on_enter.call(body)
			if once:
				a.set_deferred("monitoring", false))
	if opts.has("on_exit"):
		var on_exit: Callable = opts.on_exit
		a.body_exited.connect(func(body: Node3D) -> void:
			if body is Player:
				on_exit.call(body))
	return a


## Scatter helper: calls fn(i, Vector3 pos) n times within a rectangle (x/z), using rng.
static func scatter(n: int, rng: RandomNumberGenerator, center: Vector3, half: Vector2, fn: Callable, min_dist_from_center: float = 0.0) -> void:
	var tries := 0
	var placed := 0
	while placed < n and tries < n * 6:
		tries += 1
		var p := center + Vector3(rng.randf_range(-half.x, half.x), 0, rng.randf_range(-half.y, half.y))
		if min_dist_from_center > 0.0 and Vector2(p.x - center.x, p.z - center.z).length() < min_dist_from_center:
			continue
		fn.call(placed, p)
		placed += 1


## Direction helpers.
static func yaw_to_dir(yaw_deg: float) -> Vector3:
	return Vector3(-sin(deg_to_rad(yaw_deg)), 0, -cos(deg_to_rad(yaw_deg)))


static func dir_to_yaw(d: Vector3) -> float:
	return rad_to_deg(atan2(-d.x, -d.z))


## A simple particle emitter (dust motes, embers, snow, rain). kind: "motes"|"embers"|"rain"|"snow"|"fog"|"ash"
static func particles(parent: Node, pos: Vector3, kind: String, extent: Vector3 = Vector3(6, 3, 6), amount: int = 40) -> CPUParticles3D:
	var p := CPUParticles3D.new()
	p.position = pos
	p.amount = amount
	p.emission_shape = CPUParticles3D.EMISSION_SHAPE_BOX
	p.emission_box_extents = extent
	var qm := QuadMesh.new()
	var col := Color(1, 1, 1, 0.5)
	match kind:
		"motes":
			qm.size = Vector2(0.04, 0.04)
			p.lifetime = 6.0
			p.direction = Vector3(0, 1, 0)
			p.gravity = Vector3(0, -0.02, 0)
			p.initial_velocity_min = 0.05
			p.initial_velocity_max = 0.15
			col = Color(1, 0.95, 0.8, 0.5)
		"embers":
			qm.size = Vector2(0.06, 0.06)
			p.lifetime = 3.0
			p.direction = Vector3(0, 1, 0)
			p.gravity = Vector3(0, 0.6, 0)
			p.initial_velocity_min = 0.4
			p.initial_velocity_max = 1.2
			p.spread = 30.0
			col = Color(1, 0.45, 0.1, 0.9)
		"rain":
			qm.size = Vector2(0.02, 0.4)
			p.lifetime = 1.2
			p.direction = Vector3(0, -1, 0)
			p.gravity = Vector3(0, -14, 0)
			p.initial_velocity_min = 6.0
			p.initial_velocity_max = 8.0
			col = Color(0.7, 0.8, 1.0, 0.5)
		"snow":
			qm.size = Vector2(0.06, 0.06)
			p.lifetime = 8.0
			p.direction = Vector3(0, -1, 0)
			p.gravity = Vector3(0, -0.4, 0)
			p.initial_velocity_min = 0.2
			p.initial_velocity_max = 0.5
			p.spread = 40.0
			col = Color(1, 1, 1, 0.8)
		"ash":
			qm.size = Vector2(0.05, 0.05)
			p.lifetime = 7.0
			p.direction = Vector3(0, -1, 0)
			p.gravity = Vector3(0, -0.15, 0)
			p.initial_velocity_min = 0.1
			p.initial_velocity_max = 0.3
			p.spread = 60.0
			col = Color(0.5, 0.45, 0.45, 0.8)
		"fog":
			qm.size = Vector2(3.0, 1.2)
			p.lifetime = 9.0
			p.direction = Vector3(1, 0, 0)
			p.gravity = Vector3.ZERO
			p.initial_velocity_min = 0.2
			p.initial_velocity_max = 0.4
			col = Color(0.6, 0.65, 0.7, 0.12)
	p.mesh = qm
	var m := StandardMaterial3D.new()
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	m.albedo_color = col
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	m.billboard_mode = BaseMaterial3D.BILLBOARD_PARTICLES if kind != "rain" else BaseMaterial3D.BILLBOARD_FIXED_Y
	m.vertex_color_use_as_albedo = false
	p.material_override = m
	parent.add_child(p)
	return p


# --- layer helpers (things that only exist under certain keepsakes) -----------

static func _set_layers_recursive(node: Node, visual_layers: int, physics_layer: int) -> void:
	if node is VisualInstance3D:
		(node as VisualInstance3D).layers = visual_layers
	if node is CollisionObject3D and physics_layer >= 0:
		(node as CollisionObject3D).collision_layer = physics_layer
	for c in node.get_children():
		_set_layers_recursive(c, visual_layers, physics_layer)


## Only visible and solid while the Lantern is lit.
static func lantern_only(node: Node) -> void:
	_set_layers_recursive(node, 2, L_LANTERN_ONLY)


## Only visible and solid while looking through the Mirror Shard.
static func mirror_only(node: Node) -> void:
	_set_layers_recursive(node, 4, L_MIRROR_ONLY)


## Visible and solid only when NOT looking through the Mirror Shard.
static func normal_only(node: Node) -> void:
	_set_layers_recursive(node, 8, L_NORMAL_ONLY)


## Solid only for the full-size player (the Tin Mouse slips through).
static func big_only(node: Node) -> void:
	_set_layers_recursive(node, 1, L_BIG_ONLY)


## A mouse-hole: a dark arch in a wall that only the small player can enter.
## Places an invisible BigOnly blocker in the opening, and (unless opts.carve is
## false) punches a real opening through whatever box collision already stands
## there, so the small player has somewhere to go. opts.carve_depth sets how far
## through the wall to cut (default 1.5 m, enough for any wall in the game).
## Mouse-holes made since reset_gaps(); the verifier crawls each one at
## small-player size to prove there is somewhere to go. {pos, yaw, size, depth}
static var mouse_gaps: Array = []


static func reset_gaps() -> void:
	mouse_gaps = []


static func mouse_gap(parent: Node, pos: Vector3, yaw_deg: float, size: Vector2 = Vector2(0.45, 0.4), opts: Dictionary = {}) -> Node3D:
	var root := Node3D.new()
	root.position = pos
	root.rotation.y = deg_to_rad(yaw_deg)
	root.name = "MouseGap"
	parent.add_child(root)
	# the hole looks the size it is: the arch of the skirting prop is scaled to
	# the opening's width, and a dark box fills the wall's thickness behind it
	# (front and sides only, so from inside the crawl you can see out)
	var wall_depth := float(opts.get("wall_depth", 0.5))
	if bool(opts.get("carve", true)):
		# a carved wall keeps its mesh over the gap, so the hole is drawn through it
		box(root, Vector3(0, size.y * 0.5, wall_depth * 0.5 - 0.03), Vector3(size.x, size.y, wall_depth), "", {"tint": Color(0.02, 0.02, 0.03), "unshaded": true, "solid": false, "faces": ["nz", "px", "nx", "py", "ny"]})
	if Props.exists("skirting_hole"):
		Props.place(root, "skirting_hole", Vector3.ZERO, 0.0, size.x / 0.14, {"collision": "none"})
	else:
		var q := QuadMesh.new()
		q.size = size
		var mi := MeshInstance3D.new()
		mi.mesh = q
		mi.material_override = flat(Color(0.02, 0.02, 0.03), {"unshaded": true})
		mi.position = Vector3(0, size.y * 0.5, -0.02)
		root.add_child(mi)
	# carve first, so the big-only blocker we are about to add is not itself cut
	if bool(opts.get("carve", true)):
		var n := carve_gap(parent, pos, yaw_deg, size, float(opts.get("carve_depth", 1.5)))
		if n == 0 and bool(opts.get("expect_carve", true)):
			push_warning("mouse_gap at %s cut nothing; the hole may be blocked by non-box collision" % pos)
	var b := blocker(root, Vector3(0, size.y * 0.5, 0), Vector3(size.x, size.y, 0.3), L_BIG_ONLY)
	b.name = "BigOnlyBlocker"
	mouse_gaps.append({"pos": pos, "yaw": yaw_deg, "size": size, "depth": float(opts.get("crawl", 3.0))})
	# a hole this small is easy to walk past, so say so once, the first time the
	# full-size player stands in front of it
	var said := [false]
	trigger(parent, pos + Vector3(0, 0.9, 0), Vector3(2.2, 1.8, 2.2), func(_p: Node) -> void:
		if said[0] or Game.small:
			return
		said[0] = true
		Game.toast.emit(String(opts.get("hint", "There is a hole in the skirting board. Something small could get through there."))),
		{"name": "MouseGapHint", "continuous": true})
	return root


## Cut a rectangular opening through every axis-aligned box collider that stands
## in the way, so a mouse-hole in a MapBuilder wall is actually passable.
## The hole is `size` wide and tall with its floor at pos.y. `depth` is only how
## far along the yaw's axis a box has to reach to count as in the way; every box
## that does is bored through its whole thickness. Each blocked box is replaced by the pieces of
## itself that fall outside the hole. Returns how many boxes were cut.
static func carve_gap(area: Node, pos: Vector3, yaw_deg: float, size: Vector2, depth: float = 1.5) -> int:
	var fwd := Basis(Vector3.UP, deg_to_rad(yaw_deg)) * Vector3(0, 0, -1)
	var thru := 0 if absf(fwd.x) >= absf(fwd.z) else 2   # index of the axis we bore along
	var across := 2 if thru == 0 else 0
	var lo := Vector3(pos.x, pos.y, pos.z)
	var hi := Vector3(pos.x, pos.y + size.y, pos.z)
	lo[across] -= size.x * 0.5
	hi[across] += size.x * 0.5
	lo[thru] -= depth * 0.5
	hi[thru] += depth * 0.5
	var cut := 0
	for cs in _box_shapes(area):
		var xf: Transform3D = cs.global_transform
		var bs: BoxShape3D = cs.shape
		# only handle axis-aligned boxes; anything rotated is left alone
		if absf(xf.basis.x.y) > 0.01 or absf(xf.basis.z.y) > 0.01:
			continue
		var half := (xf.basis * (bs.size * 0.5)).abs()
		var c := xf.origin
		var bmin := c - half
		var bmax := c + half
		if bmin.x >= hi.x or bmax.x <= lo.x or bmin.y >= hi.y or bmax.y <= lo.y or bmin.z >= hi.z or bmax.z <= lo.z:
			continue
		var body: Node = cs.get_parent()
		var pieces: Array = []
		# above and below the hole keep the box's full footprint
		if bmax.y > hi.y:
			pieces.append([Vector3(bmin.x, hi.y, bmin.z), Vector3(bmax.x, bmax.y, bmax.z)])
		if bmin.y < lo.y:
			pieces.append([Vector3(bmin.x, bmin.y, bmin.z), Vector3(bmax.x, lo.y, bmax.z)])
		# either side of it, only over the hole's own height
		var y0 := maxf(bmin.y, lo.y)
		var y1 := minf(bmax.y, hi.y)
		if bmin[across] < lo[across]:
			var a := Vector3(bmin.x, y0, bmin.z)
			var bb := Vector3(bmax.x, y1, bmax.z)
			bb[across] = lo[across]
			pieces.append([a, bb])
		if bmax[across] > hi[across]:
			var a2 := Vector3(bmin.x, y0, bmin.z)
			a2[across] = hi[across]
			pieces.append([a2, Vector3(bmax.x, y1, bmax.z)])
		var parent_xf: Transform3D = (body as Node3D).global_transform
		for pc in pieces:
			var pmin: Vector3 = pc[0]
			var pmax: Vector3 = pc[1]
			var sz := pmax - pmin
			if sz.x <= 0.005 or sz.y <= 0.005 or sz.z <= 0.005:
				continue
			var ncs := CollisionShape3D.new()
			var nbs := BoxShape3D.new()
			nbs.size = sz
			ncs.shape = nbs
			body.add_child(ncs)
			ncs.global_position = (pmin + pmax) * 0.5
			ncs.global_basis = parent_xf.basis.orthonormalized()
		cs.queue_free()
		cut += 1
	return cut


static func _box_shapes(node: Node, out: Array = []) -> Array:
	if node is CollisionShape3D and (node as CollisionShape3D).shape is BoxShape3D:
		out.append(node)
	for c in node.get_children():
		_box_shapes(c, out)
	return out


# --- round rooms -------------------------------------------------------------

## A flat ring (or disc when r_in is 0) facing up (or down with opts.down). Collision: trimesh.
static func ring(parent: Node, pos: Vector3, r_in: float, r_out: float, segments: int, tex_name: String, opts: Dictionary = {}) -> MeshInstance3D:
	var tile := float(opts.get("tile", default_tile))
	var down := bool(opts.get("down", false))
	# opts.gaps: Array of [angle_deg, width_deg] sectors left open (0 = +X, 90 = +Z)
	var gaps: Array = opts.get("gaps", [])
	var quads: Array = []
	for i in segments:
		var mid_deg := 360.0 * (i + 0.5) / segments
		var skip := false
		for g in gaps:
			if absf(wrapf(mid_deg - float(g[0]), -180.0, 180.0)) < float(g[1]) * 0.5:
				skip = true
		if skip:
			continue
		var a0 := TAU * i / segments
		var a1 := TAU * (i + 1) / segments
		var p0 := Vector3(cos(a0) * r_in, 0, sin(a0) * r_in)
		var p1 := Vector3(cos(a0) * r_out, 0, sin(a0) * r_out)
		var p2 := Vector3(cos(a1) * r_out, 0, sin(a1) * r_out)
		var p3 := Vector3(cos(a1) * r_in, 0, sin(a1) * r_in)
		var uv := func(p: Vector3) -> Vector2:
			return Vector2((p.x + pos.x) / tile, (p.z + pos.z) / tile)
		if down:
			quads.append(_face(p0, p3, p2, p1, uv.call(p0), uv.call(p3), uv.call(p2), uv.call(p1), Vector3.DOWN))
		else:
			quads.append(_face(p0, p1, p2, p3, uv.call(p0), uv.call(p1), uv.call(p2), uv.call(p3), Vector3.UP))
	var mesh := mesh_from_quads(quads)
	var o := opts.duplicate()
	o["shape"] = "trimesh"
	# a ring with no collision is a mark on the ground it lies on
	if not o.has("depth_bias"):
		if not bool(opts.get("solid", true)):
			# the smaller the ring the nearer it is drawn, so rings laid on rings read in order
			o["depth_bias"] = 0.003 + 0.002 * clampf(1.0 - r_out / 10.0, 0.0, 1.0)
		else:
			o["depth_bias"] = FLOOR_BIAS
	if not o.has("surface"):
		o["surface"] = surface_of(tex_name)
	return add_mesh(parent, mesh, opts.get("mat", mat(tex_name, _mat_opts(o))), pos, o)


## A circular wall of `segments` flat panels facing inward. opts.gaps: Array of
## [angle_deg, width_deg] openings; opts.outward: also draw outward faces.
static func round_wall(parent: Node, pos: Vector3, radius: float, height: float, segments: int, tex_name: String, opts: Dictionary = {}) -> Node3D:
	var root := Node3D.new()
	root.position = pos
	root.name = String(opts.get("name", "RoundWall"))
	parent.add_child(root)
	var gaps: Array = opts.get("gaps", [])
	var o := opts.duplicate()
	o.erase("name")
	o.erase("gaps")
	for i in segments:
		var a_mid := 360.0 * (i + 0.5) / segments
		var skip := false
		for g in gaps:
			var diff := absf(wrapf(a_mid - float(g[0]), -180.0, 180.0))
			if diff < float(g[1]) * 0.5:
				skip = true
		if skip:
			continue
		var a0 := deg_to_rad(360.0 * i / segments)
		var a1 := deg_to_rad(360.0 * (i + 1) / segments)
		var p0 := Vector3(cos(a0) * radius, 0, sin(a0) * radius)
		var p1 := Vector3(cos(a1) * radius, 0, sin(a1) * radius)
		wall(root, p1, p0, height, tex_name, o)
	return root


## Polar helper: a point on a circle in the XZ plane. angle_deg 0 = +X, 90 = +Z.
static func polar(radius: float, angle_deg: float, y: float = 0.0) -> Vector3:
	return Vector3(cos(deg_to_rad(angle_deg)) * radius, y, sin(deg_to_rad(angle_deg)) * radius)


## Yaw (in Kit convention, 0 = facing -Z) that looks from a point on a circle toward its centre.
static func yaw_to_center(angle_deg: float) -> float:
	return dir_to_yaw(-polar(1.0, angle_deg))
