extends Node
## Audio — ambience crossfades and one-shot sound effects. Autoloaded as `Audio`.
##
## Streams are WAV files generated by tools/gen_assets/audio.py. Missing files
## are tolerated (silently skipped) so the game and its tests run before assets
## exist, and so new areas can be prototyped without sound.

const AMB_DIR := "res://assets/audio/ambience/"
const SFX_DIR := "res://assets/audio/sfx/"
const AMB_VOLUME_DB := -8.0
const POOL_SIZE := 12

var _amb: Array[AudioStreamPlayer] = []
var _amb_active := 0
var _current_amb := ""
var _sfx3d: Array[AudioStreamPlayer3D] = []
var _sfx2d: Array[AudioStreamPlayer] = []
var _cache: Dictionary = {}
var _tweens: Array = [null, null]
var muted := false


func _ready() -> void:
	for i in 2:
		var p := AudioStreamPlayer.new()
		p.volume_db = -80.0
		p.bus = "Master"
		add_child(p)
		_amb.append(p)
	for i in POOL_SIZE:
		var p2 := AudioStreamPlayer.new()
		add_child(p2)
		_sfx2d.append(p2)


func _stream(path: String) -> AudioStream:
	if _cache.has(path):
		return _cache[path]
	var s: AudioStream = null
	if ResourceLoader.exists(path):
		s = load(path)
	_cache[path] = s
	return s


func _looped(s: AudioStream) -> AudioStream:
	# Loops generated by tools/gen_assets/audio.py carry a `smpl` chunk, so the
	# importer already sets LOOP_FORWARD. This fallback only handles plain PCM
	# files without one (QOA-compressed imports keep whatever the importer chose).
	if s is AudioStreamWAV:
		var w: AudioStreamWAV = s
		if w.loop_mode == AudioStreamWAV.LOOP_DISABLED and (w.format == AudioStreamWAV.FORMAT_16_BITS or w.format == AudioStreamWAV.FORMAT_8_BITS):
			w.loop_mode = AudioStreamWAV.LOOP_FORWARD
			var bytes_per_frame := 2 if w.format == AudioStreamWAV.FORMAT_16_BITS else 1
			if w.stereo:
				bytes_per_frame *= 2
			w.loop_begin = 0
			w.loop_end = int(w.data.size() / bytes_per_frame)
	return s


## Crossfade to a named ambience loop (assets/audio/ambience/<name>.wav). "" stops.
func set_ambience(ambience_name: String, fade: float = 2.5) -> void:
	if ambience_name == _current_amb:
		return
	_current_amb = ambience_name
	var next_i := 1 - _amb_active
	var old := _amb[_amb_active]
	var nxt := _amb[next_i]
	var s: AudioStream = null
	if ambience_name != "":
		s = _stream(AMB_DIR + ambience_name + ".wav")
	if _tweens[0]:
		_tweens[0].kill()
	if _tweens[1]:
		_tweens[1].kill()
	var t_old := create_tween()
	t_old.tween_property(old, "volume_db", -80.0, fade)
	t_old.tween_callback(old.stop)
	_tweens[0] = t_old
	if s != null:
		nxt.stream = _looped(s)
		nxt.volume_db = -80.0
		nxt.play()
		var t_new := create_tween()
		t_new.tween_property(nxt, "volume_db", AMB_VOLUME_DB if not muted else -80.0, fade)
		_tweens[1] = t_new
	_amb_active = next_i


## Bend the ambience loop's pitch (the King's Dream drops it while the hour is held).
func set_ambience_pitch(pitch: float, fade: float = 0.8) -> void:
	for p in _amb:
		var tw := create_tween()
		tw.tween_property(p, "pitch_scale", clampf(pitch, 0.25, 2.0), fade)


## Play a one-shot effect. If `at` is a Vector3 the sound is positional (in the
## current area's space); otherwise it is a flat UI sound.
func sfx(sfx_name: String, at: Variant = null, volume_db: float = 0.0, pitch_jitter: float = 0.06) -> void:
	if muted:
		return
	var s := _stream(SFX_DIR + sfx_name + ".wav")
	if s == null:
		return
	var pitch := 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	if at is Vector3 and World.area_root != null:
		var p3 := _get_3d()
		p3.global_position = at
		p3.stream = s
		p3.volume_db = volume_db
		p3.pitch_scale = pitch
		p3.play()
	else:
		for p in _sfx2d:
			if not p.playing:
				p.stream = s
				p.volume_db = volume_db
				p.pitch_scale = pitch
				p.play()
				return


func _get_3d() -> AudioStreamPlayer3D:
	for p in _sfx3d:
		if not p.playing and p.get_parent() == World.area_root:
			return p
	var p := AudioStreamPlayer3D.new()
	p.max_distance = 40.0
	p.unit_size = 4.0
	World.area_root.add_child(p)
	_sfx3d.append(p)
	return p


func set_muted(m: bool) -> void:
	muted = m
	for p in _amb:
		p.volume_db = -80.0 if m else AMB_VOLUME_DB
